version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mlops-app

permissions:
  - object: /home/ec2-user/mlops-app
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user
